version: '2'
services:
  insomniaboxclient:
    image: insomniabox-client

  insomniaboxserver:
    image: insomniabox-server
    environment:
      - PORT=80
    env_file:
      - ./server/.env

  proxy:
    image: insomniabox-nginx
    ports:
      - "8080:80"
