version: '2'
services:
  insomniaboxclient:
    build: 
      context: ./client
      args:
        API_BASE_URL: '/api'
        USE_FAKE: 'false'
        RELOAD_INTERVAL: 60

  insomniaboxserver:
    build: ./server
    environment:
      - PORT=80
    env_file:
      - ./server/.env

  proxy:
    build: ./nginx
    ports:
      - "8080:80"
