version: '2'
services:
  insomniaboxclient:
    build: ./client/Dockerfile.raspberry
    environment:
      - API_BASE_URL=/api
      - USE_FAKE=false
    # ports:
      #- "5001:80"
  insomniaboxserver:
    build: ./server/Dockerfile.raspberry
    environment:
      - PORT=80
    env_file:
      - ./server/.env
    # ports:
      # - "5000:80"
  proxy:
    build: ./nginx/Dockerfile.raspberry
    ports:
      - "8080:80"
