version: '2'
services:
  insomniaboxclient:
    image: insomniabox-client
    environment:
      - API_BASE_URL=/api
      - USE_FAKE=false
    # ports:
      #- "5001:80"
  insomniaboxserver:
    image: insomniabox-server
    environment:
      - PORT=80
    env_file:
      - ./server/.env
    # ports:
      # - "5000:80"
  proxy:
    image: insomniabox-nginx
    ports:
      - "8080:80"
