### Find station
GET http://localhost:3001/tube/stations?name=Mälarhöjden
Accept: application/json

### Get metro
GET http://localhost:3001/tube/stations/9290/realtime
Accept: application/json

### Test
GET http://localhost:3001/test
Accept: application/json


